// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
import { z } from "npm:zod@^4.4.3";
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List upcoming/available events (ingressos) from TicketHub BH. Optionally filter by music genre/category or a text query matching title or venue.",
  inputSchema: {
    category: z.string().optional().describe("Genre/category filter (e.g. FUNK, SERTANEJO, PAGODE, ROCK, POP)."),
    query: z.string().optional().describe("Case-insensitive substring to match against event title or venue."),
    limit: z.number().int().positive().max(100).optional().describe("Max number of results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, query, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("eventos").select("id,titulo,sobre,data,hora,local,categoria,preco,imgUrl").order("_ts", { ascending: true });
    if (category) q = q.eq("categoria", category);
    const { data, error } = await q.limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const filtered = query ? (data ?? []).filter((e) => {
      const s = query.toLowerCase();
      return e.titulo?.toLowerCase().includes(s) || e.local?.toLowerCase().includes(s);
    }) : data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(filtered) }],
      structuredContent: { events: filtered }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Get event details",
  description: "Fetch full details for a single event by its ID, including attractions, ticket links, venue, and dates.",
  inputSchema: {
    id: z2.string().min(1).describe("Event ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("eventos").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No event with id ${id}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/list-albums.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_albums_default = defineTool3({
  name: "list_photo_albums",
  title: "List photo albums",
  description: "List photo albums (galerias) from past events on TicketHub BH.",
  inputSchema: {
    limit: z3.number().int().positive().max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("albuns").select("id,nome,data,capa,link").order("_ts", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { albums: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "tickethub-bh-mcp",
  title: "TicketHub BH",
  version: "0.1.0",
  instructions: "Public data from TicketHub BH \u2014 events/tickets and photo albums. Use list_events / get_event to discover upcoming shows in Belo Horizonte, and list_photo_albums for past-event galleries.",
  tools: [list_events_default, get_event_default, list_albums_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
